### ISSUE TITLE
Component 'MSCOMCTL.OCX or one of its dependencies not correctly registered: a file is missing or invalid 

### ISSUE THREAD

**Issue by phtom** [scipag/httprecon-win32#1]
Hi, i am getting this error:"Component 'MSCOMCTL.OCX or one of its dependencies not correctly registered: a file is missing or invalid"

I tried many fixes but none of them works. What can i do to fix this?

**Comment by marcruef** [comment]
_OCX_ files are _ActiveX controls_ which act like libraries (e.g. DLL). You have to _download_ the OCX file which matches your windows version (e.g. Win7, Win10) and architecture (e.g. x86, x64). Then you have [to register the file](https://support.microsoft.com/en-us/help/2746232/how-to-register-an-activex-control-manually-ocx) on the command line as administrator by entering `Regsvr32 /s c:\windows\system32\mscomctl.ocx`.

**Comment by GrayFace** [comment]
Solution: Download https://www.microsoft.com/en-us/download/details.aspx?id=10019 and extract with an archive manager instead of installing.
